### ISSUE TITLE
Add credentials node

### ISSUE THREAD

**Issue by krzysiekpiasecki** [SymfonyCollection/DotpayBundle#19]
```yml
# app/config/config.yml

dotpay:
    credentials:
         id: xxxxxx
         pin: xxxxxx
    urlc: route_to_urlc
```
