### ISSUE TITLE
Enviroment Configuration

### ISSUE THREAD

**Issue by krzysiekpiasecki** [SymfonyCollection/DotpayBundle#25]

**Comment by krzysiekpiasecki** [comment]
```yml
# app/config/config.yml

dotpay:
    credentials:
         id: xxxxxx
         pin: xxxxxx
    urlc: route_to_urlc
```
